### ISSUE TITLE
Is this project under the MIT license? Can I integrate it into a commercial project？

### ISSUE THREAD

**Issue by chengfengfengwang** [tldraw/vite-template#1]

**Comment by SomeHats** [comment]
The code in this repo is MIT. The tldraw component, which this repo uses, is available under the [tldraw license](https://github.com/tldraw/tldraw/blob/main/LICENSE.md). So although you can take the code here and do what you want with it, if you wanted to deploy tldraw you would still need to buy a license from us.

**Comment by Wonko7** [comment]
Could you elaborate please? Reading the license it sounds like you can run your own instance as long as you leave the watermark & license. What am I missing?

**Comment by SomeHats** [comment]
Our license has actually changed a little since I posted this comment, but yes, you're essentially right: you can use tldraw in your code as long as you keep the water mark. If you want to remove the watermark, you need to purchase a license.
